# ./docker-compose.yml

version: '3'

services:
  db:
    build: ./build_db
    container_name: dockertest_mysql_56    
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "9906:3306"
  web:
    build: ./build_web
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PASSWORD=${DB_PASSWORD}
    container_name: dockertest_php71_web
    depends_on:
      - db
    volumes:
      - ./src/:/var/www/html/
    ports:
      - "8100:80"
    stdin_open: true
    tty: true